### ISSUE TITLE
Atualização do conteúdo das páginas

### ISSUE THREAD

**Issue by PedroVNasc** [CRInt-ICMC/crint-site#39]
O novo formato exige certas adaptações ao conteúdo antigo, além de reescrição dos textos para um linguajar mais moderno e que se adapte à realidade atual da USP.

**Comment by KrulesExGamer** [comment]
Idealmente, todas as funcionalidades do DIA e as entrevistas dos alunos devem estar prontas nessa versão.

**Comment by KrulesExGamer** [comment]
Talvez tenha que ser adiado para a versão 1.3, devido ao tema geral dessa versão estar centrado na otimização e generalização do conteúdo.
