### ISSUE TITLE
Feed de notícias

### ISSUE THREAD

**Issue by CRInt-ICMC** [CRInt-ICMC/crint-site#4]
Idealmente, o site deveria conter um feed de notícias relevantes à CRInt. Esse feed poderia ser alimentado manualmente ou através de uma API ou, em último recurso, _scrapping_ de fontes relevantes como o jornal da USP e a AUCANI.

O feed pode ter uma página própria ou estar disponível em alguma área da _Home_. Não é necessário que ele seja atualizado em tempo real, apesar de que idealmente atualizações diárias ou de hora em hora deveriam ser realizadas.

**Comment by CRInt-ICMC** [comment]
Essa funcionalidade deve ser reconsiderada e discutida em uma próxima reunião, pois possivelmente escapou ao escopo do projeto.

**Comment by KrulesExGamer** [comment]
Afinal mesmo se o Telegram ou o Instagram for integrado, já não será um feed de notícias como a ideia original. Além disso, escapa do escopo do site ter esse feed, pois nem todas as notícias dessas fontes são relevantes para a CRInt do ICMC.
