### ISSUE TITLE
Licensiamento

### ISSUE THREAD

**Issue by CRInt-ICMC** [CRInt-ICMC/crint-site#5]
É necessário que antes de o código ser disponibilizado publicamente, seja estudada a licença de distribuição. Idealmente, a licença deverá permitir que interessados copiem partes ou a totalidade do código para uso pessoal. Porém, devem haver restrições para que não haja apropriação dos créditos e nem seja utilizado para personificar a CRInt.

Em resumo, a licença deve ser código aberto, porém com restrições legais para que sejam dados os devidos créditos em caso de uso profissional e que não permita que o código seja utilizado para fins de personificação ilegal da CRInt.

**Comment by KrulesExGamer** [comment]
GPLv3 é o padrão do instituto.
