### ISSUE TITLE
Avaliar a possibilidade de mudar de React para Solid

### ISSUE THREAD

**Issue by CRInt-ICMC** [CRInt-ICMC/crint-site#72]
Também deve ser avaliado as vantagens e desvantagens, além das mudanças de documentação e o tempo de desenvolvimento necessários.

**Comment by KrulesExGamer** [comment]
Há certas complicações nesse processo como o aprendizado de uma nova linguagem, a refatoração da documentação e a possibilidade de que alguns pacotes não sejam compatíveis, em especial, o VLibras.

**Comment by KrulesExGamer** [comment]
No momento, não há razão para fazer essa mudança.
